# -*- coding: utf-8 -*-
"""Novelty_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvYHjHhhYsvTULWIFB6W_Uijj8EHtslJ
"""

absolute_path = os.path.dirname("/content/drive/MyDrive/Podocarpus_Final/")

# Define Shannon Entropy First
def myEntropy(p, dim = -1, keepdim=False):
    return -torch.where(p > 0, p * torch.log(p), p.new([0.0])).sum(dim = dim, keepdim=keepdim)

# Load Fused Porbabilities from pollen classification notebook
Fused_Probabilities_Normalized = pd.read_csv(absolute_path + "/Fused_Probabilities_Normalized.csv", header = None)

# Compute Entropy over Softmax Stacked probability vectors (associated with test images)
Shannon_Fused = myEntropy(Fused_Probabilities_Normalized)
print(Shannon_Fused.shape)
print('Fused Shannon Entropy: {}'.format(Shannon_Fused))